#version: '3.8'
services:
  backend:
    container_name: pdns-etcd3-backend
    image: debian:12-slim
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./pdns-etcd3:/pdns-etcd3:ro
      - common:/common
  pdns:
    container_name: pdns-etcd3-pdns
    image: powerdns/pdns-auth-45
    volumes:
      - common:/common
      - ./pdns.conf:/etc/powerdns/pdns.conf:ro
      - ./pdns-etcd3:/pdns-etcd3:ro
    ports:
      - "${PDNS_PUBLIC_TCP_PORT:-${PDNS_PUBLIC_PORT:-}}:53"
      - "${PDNS_PUBLIC_UDP_PORT:-${PDNS_PUBLIC_PORT:-}}:53/udp"
    depends_on:
      - backend
  etcd:
    container_name: pdns-etcd3-etcd
    image: quay.io/coreos/etcd:${ETCD_IMAGE_VERSION:-v3.5.14}
    volumes:
      - etcd-data:/data
    command: |
      etcd
      --data-dir=/data
      --name=etcd
      --initial-advertise-peer-urls=http://etcd:2380
      --listen-peer-urls=http://0.0.0.0:2380
      --advertise-client-urls=http://etcd:2379
      --listen-client-urls=http://0.0.0.0:2379
      --initial-cluster=etcd=http://etcd:2380
      --auto-compaction-retention=1h
    ports:
      - "${ETCD_PUBLIC_CLIENT_PORT:-}:2379"
    restart: unless-stopped

volumes:
  etcd-data:
  common:
