FROM debian:12-slim
ADD etcdkeeper.sh /opt/
ADD https://github.com/evildecay/etcdkeeper/releases/download/v0.7.8/etcdkeeper-v0.7.8-linux_x86_64.tar.gz /opt/
WORKDIR /opt
RUN <<EOF
set -ex
tar -xf etcdkeeper*.tar.gz
chmod +x etcdkeeper etcdkeeper.sh
export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get install -y simpleproxy
EOF
ENV ETCD_ENDPOINT=""
ENTRYPOINT exec ./etcdkeeper.sh "$ETCD_ENDPOINT"
EXPOSE 8080/tcp
