name: Build and Upload

on:
  workflow_dispatch:
    inputs:
      checkout_ref:
        description: 'Commit SHA, branch name, or tag to build (e.g. master, v1.2.3, a1b2c3d).'
        required: true
        default: 'release'
      go_version:
        description: 'Go version to use (e.g. 1.26)'
        required: true
        default: '1.26'

permissions:
  contents: read
  actions: write

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.inputs.checkout_ref }}
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ github.event.inputs.go_version }}
      - name: Build
        env:
          GOOS: linux
          GOARCH: amd64
          CGO_ENABLED: 0
        run: |
          set -ex
          BUILD_TAG=${{ github.event.inputs.checkout_ref }}_linux_amd64
          go build -o pdns-etcd3_${BUILD_TAG} -a -ldflags="-extldflags=-static -X main.gitVersion=$(git describe --always --dirty)"
          ./pdns-etcd3_${BUILD_TAG} -help
      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          path: pdns-etcd3_*
          archive: false
